exports.USER_STATUS = {
  unconfirmed_user: 'NEWUSER',
  confirmed_user: 'USRA',
  confirmed_user_officer: 'USRS',
  confirmed_vendor: 'VDRA',
  confirmed_vendor_officer: 'VDRS',
  sysadmin: 'SADM',
}
exports.COMPANY_STATUS = {
  shipper: 'USER',
  vendor: 'VENDOR',
  sysadmin: 'ANDALIN',
}

exports.SHIPMENTLOAD_TYPES = {
  LCL: 'lcl',
  FCL: 'fcl',
  AIRCARGO: 'aircargo',
  AIRCOURIER: 'aircourier',
}
exports.CONTAINER_TYPES = {
  FT20: 'ft20',
  FT40: 'ft40',
  HC40: 'ft40hc',
  REEFER: 'reefer',
  VENTILATE: 'ventilate',
}
exports.SERVICE_TYPES = {
  AIRCARGO: 'AIRCARGO',
  AIRCOURIER: 'AIRCOURIER',
  SEALCL: 'SEALCL',
  FT20: 'SEAFCL20FT',
  FT40: 'SEAFCL40FT',
  HC40: 'SEAFCL40FTHC',
  REEFER: 'REF',
  VENTILATE: 'VENT',
  UNKNOWN: 'UNKNOWN',
}
exports.ORDER_TYPES = {
  PTP: 'PTP',
  PTD: 'PTD',
  DTD: 'DTD',
  DTP: 'DTP',
}
exports.HISTORY_ACTION = {
  REQUEST: {
    ADD: 'ADD REQUESTS',
    UPDATE: 'UPDATE REQUESTS',
  },
  PRICE: {
    ADD: 'ADD PRICES',
  },
  ORDER_STATUS: {
    UPDATE: 'UPDATE ORDER STATUS',
  },
  INVOICE: {
    ADD: 'ISSUED INVOICE',
  },
  SCHEDULE: {
    ADD: 'ADD SCHEDULE',
  },
  PAYMENT: {
    ADD: 'ADD PAYMENT',
  },
  CARRIER: {
    UPDATE: 'UPDATE CARRIER',
  },
  COMMODITIES: {
    UPDATE: 'UPDATE COMMODITIES',
  },
  SHIPPER_CONSIGNEE: {
    UPDATE: 'UPDATE SHIPPER CONSIGNEE',
  },
  FREIGHT: {
    UPDATE: 'UPDATE FREIGHT',
  },
  DOCUMENT: {
    UPLOAD: 'UPLOAD DOCUMENT',
  },
}

exports.WEBSOCKET = {
  WEBSOCKET_JOIN_ROOM: 'WEBSOCKET_JOIN_ROOM',
  RECEIVE_WEBSOCKET_NEW_SUBSCRIBER: 'RECEIVE_WEBSOCKET_NEW_SUBSCRIBER',
  RECEIVE_WEBSOCKET_BOOK_SHIPMENT: 'RECEIVE_WEBSOCKET_BOOK_SHIPMENT',
  RECEIVE_WEBSOCKET_JOINED_ROOM: 'RECEIVE_WEBSOCKET_JOINED_ROOM',
  RECEIVE_WEBSOCKET_UPDATE_SHIPMENT_SHIPPER_CONSIGNEE: 'RECEIVE_WEBSOCKET_UPDATE_SHIPMENT_SHIPPER_CONSIGNEE',
  RECEIVE_WEBSOCKET_UPDATE_SHIPMENT_ORDER_STAT: 'RECEIVE_WEBSOCKET_UPDATE_SHIPMENT_ORDER_STAT',
  RECEIVE_WEBSOCKET_UPDATE_SHIPMENT_COMMODITIES: 'RECEIVE_WEBSOCKET_UPDATE_SHIPMENT_COMMODITIES',
  RECEIVE_WEBSOCKET_UPDATE_SHIPMENT_CARRIER: 'RECEIVE_WEBSOCKET_UPDATE_SHIPMENT_CARRIER',
  RECEIVE_WEBSOCKET_UPDATE_SHIPMENT_REQUESTS: 'RECEIVE_WEBSOCKET_UPDATE_SHIPMENT_REQUESTS',
  RECEIVE_WEBSOCKET_UPDATE_SHIPMENT_FREIGHTS: 'RECEIVE_WEBSOCKET_UPDATE_SHIPMENT_FREIGHTS',
  RECEIVE_WEBSOCKET_UPDATE_SHIPMENT_ORDER_PRICE: 'RECEIVE_WEBSOCKET_UPDATE_SHIPMENT_ORDER_PRICE',
  RECEIVE_WEBSOCKET_UPDATE_SHIPMENT_DOCUMENTS: 'RECEIVE_WEBSOCKET_UPDATE_SHIPMENT_DOCUMENTS',
  RECEIVE_WEBSOCKET_UPDATE_SHIPMENT_MESSAGES: 'RECEIVE_WEBSOCKET_UPDATE_SHIPMENT_MESSAGES',
  WEBSOCKET_JOIN_ROOM_RFQ: 'WEBSOCKET_JOIN_ROOM_RFQ',
  RECEIVE_WEBSOCKET_UPDATE_SHIPMENT_TOP: 'RECEIVE_WEBSOCKET_UPDATE_SHIPMENT_TOP',
}
